version: '2.1'

services:
  dbmaster:
    build: dbmaster
    volumes:
    - pdns_cluster_dbmaster_mysql:/var/lib/mysql
    environment:
    - DBMASTER_PASSWORD_pdns=dbmasterpw
    networks:
      pdns_net:
        ipv4_address: 10.0.1.2
    logging:
      driver: "json-file"

  dbslave:
    build: dbslave
    volumes:
    - pdns_cluster_dbslave_mysql:/var/lib/mysql
    environment:
    - DBSLAVE_PASSWORD_pdns=dbslavepw
    networks:
      pdns_net:
        ipv4_address: 10.0.1.3
    logging:
      driver: "json-file"

  nsmaster:
    build: nsmaster
    ports:
    - "8081:8081"
    environment:
    - DBMASTER_PASSWORD_pdns=dbmasterpw
    - NSMASTER_APIKEY=nsmasterapikey
    depends_on:
    - dbmaster
    networks:
      pdns_net:
        ipv4_address: 10.0.1.4
    logging:
      driver: "json-file"

  nsslave:
    build: nsslave
    environment:
    - DBSLAVE_PASSWORD_pdns=dbslavepw
    - NSSLAVE_APIKEY=nsslaveapikey
    depends_on:
    - dbslave
    networks:
      pdns_net:
        ipv4_address: 10.0.1.5
    logging:
      driver: "json-file"

volumes:
  pdns_cluster_dbmaster_mysql:
  pdns_cluster_dbslave_mysql:

networks:
  pdns_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
        gateway: 10.0.1.1
